export const KEY_STORE = {
  TOKEN_AUTH: 'TOKEN_AUTH',
  TOKEN_FIREBASE: 'TOKEN_FIREBASE',
  REFRESH_AUTH: 'REFRESH_AUTH',
  FCM_TOKEN: 'FCM_TOKEN',
  CHANNEL_NOTIFICATION: 'CHANNEL_NOTIFICATION',
};
