export const SCREEN_NAME = {
  STACK_HOME_SCREEN: 'STACK_HOME_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  AUTH_SCREEN: 'AUTH_SCREEN',
  CONFIRM_OTP_SCREEN: 'CONFIRM_OTP_SCREEN',
  CREATE_PASSWORD_SCREEN: 'CREATE_PASSWORD_SCREEN',
  CHANGE_PASSWORD_SCREEN: 'CHANGE_PASSWORD_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
};
